version: '3.6'

services:
    
    entities:
        build:
            context: ./services/entities
            dockerfile: Dockerfile
        volumes:
            - './services/entities:/usr/src/entities'
        ports:
            - 5001:5000
        environment:
            - FLASK_ENV=development
            - APP_SETTINGS=project.config.Config
            - DATABASE_URL=postgres://postgres:postgres@persistence-db:5432/entities
        depends_on:
            - persistence-db
            
    
    persistence-db:
        build:
            context: ./services/databases/persistence
            dockerfile: Dockerfile
        ports:
            - 5435:5432
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            
    
    web-ui:
        build:
            context: ./services/web-ui
            dockerfile: Dockerfile
        volumes:
            - './services/web-ui:/usr/src/web-ui'
            - '/usr/src/web-ui/node_modules'
        ports:
            - 3007:3000
        environment:
            - NODE_ENV=development
            - REACT_APP_ENTITIES_SERVICE_URL=http://localhost
        depends_on:
            - entities